### ISSUE TITLE
UI broken no novo Microsoft Edge

### ISSUE THREAD

**Issue by oilervoss** [pedrohsoaresadv/sei-pro#1]
Microsft Edge 87.0.664.75 (Compilação oficial) (64 bits)
SEI Pro 0.1.21.1
Windows 10 64 bits

![Capturar](https://user-images.githubusercontent.com/23159753/105191562-ffdc4a80-5b15-11eb-82f2-d05bbb602218.PNG)

**Comment by oilervoss** [comment]
E parabéns pelo ótimo trabalho!

**Comment by pedrohsoaresadv** [comment]
Interessante, @oilervoss Não fiz nenhum teste da extensão com o Microsft Edge. Vou fazer os testes aqui e implementar a correção no modal de configurações.

**Comment by pedrohsoaresadv** [comment]
Olá @oilervoss 
Pesquisei e tentei arrumar, mas parece que é um bug do Edge 

https://techcommunity.microsoft.com/t5/discussions/extension-settings-window-is-too-small/m-p/985982/highlight/true#M15881

Vou ficar de olho, quando ajustarem eu comunico contigo.
