### ISSUE TITLE
Erro na versão 0.1.26.19

### ISSUE THREAD

**Issue by PeterGriffinBR** [pedrohsoaresadv/sei-pro#11]
Boa tarde! Estou usando a versão 0.1.26.19 no Chrome Versão 93.0.4577.82.

O erro aparece quando:

1 - Entro na tela inicial da lista de processos;
2 - Seleciono "Agrupar processos por responsável";
3- Há processos ainda "não atribuídos".

O que ocorre: a lista de processos fica alternando a classificação a cada segundo, ou seja, fica (mais ou menos) piscando. É difícil explicar, mas a lista fica variando, como se estivesse reordenando a cada segundo.

**Comment by pedrohsoaresadv** [comment]
Olá @PeterGriffinBR 

De fato está ocorrendo esse problema. Já identifiquei e submeti a atualização da Versão 0.1.26.20. Em breve estará disponível no Chrome e Firefox

Ps.: Chrome demora até 3 dias pra liberar as atualizações. Firefox sairá ainda hoje.

Atenciosamente,

Pedro
