### ISSUE TITLE
Agrupar processos quando há mais de 100 processos na unidade

### ISSUE THREAD

**Issue by leosouza85** [pedrohsoaresadv/sei-pro#2]
Quando há mais de 100 processos na unidade, é gerada uma outra página, com uma setinha para mostrar o resto. Estes processos não são levados em consideração nos agrupamentos da extensão, o que acaba tornando prejudicado o agrupamento por não considerar todos os processos. Isso pode até gerar uma confusão por ficar um processo de uma data x, perdido na outra página.

**Comment by pedrohsoaresadv** [comment]
De fato, @leosouza85 
Vou analisar essa circunstância e estudar uma maneira de contornar a paginação de processos na página inicial do SEI. Obrigado pela contribuição de melhoria!

**Comment by pedrohsoaresadv** [comment]
Adicionada remoção de paginação de processos na versão 0.1.23! Valeu @leosouza85 pela contribuição de melhoria!
