### ISSUE TITLE
Os agrupamentos não abarcam todos os processos.

### ISSUE THREAD

**Issue by leosouza85** [pedrohsoaresadv/sei-pro#3]
Tenho notado que não importando a unidade em que eu esteja, considerando apenas unidades que não tenham 100 ou mais processos, ou seja que todos os processos ficam na tela, ficam sempre alguns processos não agrupados na parte de cima, seja agrupamento por data de recebimento, por data de envio ou por setor de envio. Estes processos não se tratam de processos gerados na unidade, mas recebidos de outra.

**Comment by pedrohsoaresadv** [comment]
@leosouza85 Os agrupamentos por data de recebimento, por data de envio ou por setor de envio utilizam os dados do histórico do processo. 

O script acessa o processo e recupera as informações disponíveis no link "Consultar Andamento". Certamente esses processos não contêm a descrição `Processo recebido na unidade`, `Reabertura do processo na unidade` ou `Processo público` gerado e que corresponda a sua unidade.

De qualquer forma, me envie um print da sua tela no pedrohsoares.adv@gmail.com Assim posso analisar melhor essa situação.

**Comment by pedrohsoaresadv** [comment]
Lançado melhorias no agrupamento de processos na versão 0.1.23. Valeu @leosouza85 pela contribuição de melhoria!
