### ISSUE TITLE
Separar o cache de agrupamento por unidade.

### ISSUE THREAD

**Issue by leosouza85** [pedrohsoaresadv/sei-pro#4]
Usuários que atuam em mais de uma unidade acabam refazendo todo o agrupamento ao mudar de unidade, o que é demorado dependendo da quantidade de processos. Se cada unidade que você acessou tiver seu próprio cache, ele só vai fazer o processo demorado na primeira vez que a unidade é acessada.

:-)

**Comment by pedrohsoaresadv** [comment]
Segregação de cache da seleção de agrupamento por unidade adicionada na versão 0.1.23. Valeu @leosouza85 pela contribuição de melhoria!
