### ISSUE TITLE
Menu se deslocando para baixo da página

### ISSUE THREAD

**Issue by tcgontijo** [pedrohsoaresadv/sei-pro#5]
Em algumas situações quando se clica sobre o link "Menu" para escondê-lo/mostrá-lo ele se desloca para baixo da página e somente retorna ao local de origem se a página for atualizada.

Como alguns monitores são pequenos e o menu lateral do SEI consome um espaço considerável da tela esse recurso é muito útil.

Ainda não identifiquei um padrão para que o bug ocorra. Verifiquei aqui e quando desabilito a extensão o funcionamento se regulariza.

Portanto, se for possível verificar o que pode estar ocorrendo.

No mais, parabéns pelo trabalho! A extensão é muito boa mesmo! Melhorou demais o editor de texto que era muito rudimentar, sem contar nas outras funcionalidades!

[Microsoft Windows 10 Enterprise LTSC - 64bits
Google Chrome Versão 88.0.4324.182 (Versão oficial) 64 bits ]

![Capturar](https://user-images.githubusercontent.com/64798940/108858264-bbd3de00-75ca-11eb-877f-552c70dcddcd.PNG)

**Comment by pedrohsoaresadv** [comment]
@tcgontijo Obrigado pelo feedback
Não consegui reproduzir o erro por aqui. Por gentileza, envie um email para pedrohsoares.adv@gmail.com Assim posso analisar melhor essa situação.

**Comment by tcgontijo** [comment]
Oi Pedro, valeu pela atenção! Eu fui tentar reproduzir aqui e acabei descobrindo que este bug ocorre quando utilizo o SEI Pro junto com outra extensão, o SEI++. Acho que deve ter alguma incompatibilidade entre as extensões, visto que devem manipular ações similares. Como eu já uso o SEI++ há algum tempo e aqui na minha Unidade é quase que um requisito para os servidores é complicado me desfazer. Porém não vou me desfazer do SEI Pro de jeito nenhum também! Na verdade estou conseguindo trabalhar bem com as duas e este bugzinho não está sendo tão incômodo.

Enfim, acho que vou encerrar esse _Issue_ porque não há nada de errado com sua extensão.
