### ISSUE TITLE
Acompanhamento de projetos

### ISSUE THREAD

**Issue by cbiazin** [pedrohsoaresadv/sei-pro#7]
Estou desde ontem tentando habilitar o acompanhamento de processos, mas sempre dá algo errado.
Ontem, dava erro ao tentar ligar a função, até que descobri que é necessário publicar o app (não constava do passo a passo)
Agora a função aparece, mas não consigo inserir nem modificar projetos, os botões parecem que não funcionam.
Devido à dificuldade, acho que essa funcionalidade merecia um vídeo-tutorial próprio.

**Comment by pedrohsoaresadv** [comment]
Olá @cbiazin 

Sobre o erro, tenho uma ideia do que pode estar passando aí. Por isso lancei ontem a versão 0.1.24 que corrige isso. Veja agora como está e me informe.

Sobre a etapa de publicar o app, averiguei aqui e o Google Cloud adicionou mais essa etapa no painel deles, vou atualizar o tutorial. Pretendo em breve incluir um vídeo sobre isso também.

Valeu pelo feedback
