### ISSUE TITLE
Upload não funciona caso não exista o tipo de documento "Anexo"

### ISSUE THREAD

**Issue by franklinbaldo** [pedrohsoaresadv/sei-pro#8]
Desconsiderar. A funcionalidade que eu estava pedindo já existe. 
Parabéns.

**Comment by pedrohsoaresadv** [comment]
Olá @franklinbaldo 

Tranquilo, vou deixar o registro aqui, para outros usuários.

O padrão "Anexo" é utilizado como padrão para o upload de vários arquivos pela árvore. Para esses casos excepcionais, como o do seu órgão, recomendo alterar o padrão de arquivo lá nas opções do SEI Pro

![image](https://user-images.githubusercontent.com/54042592/125686065-3e27b051-cd72-4c4e-88a5-ecf754fa3db4.png)

Dessa forma todos os anexos carregados pela árvore do processo já utilizarão a nova nomenclatura "Relatório", no lugar do padrão "Anexo"
